 pgadmin:
   image: dpage/pgadmin4
   depends_on:
     - postgresql
   ports:
     - "5555:80"
   environment:
     PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
     PGADMIN_DEFAULT_PASSWORD: admin
   restart: unless-stopped
network_mode: host 